baseURL = 'https://www.whatgenerativeai.com/'
languageCode = 'en-us'
title = 'What Generative AI'
theme = 'hugo-book'

[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/dipankar"
  weight = 10
