baseURL = 'https://www.whatgenerativeai.com/'
languageCode = 'en-us'
title = 'What Generative AI'
theme = 'hugo-book'

[languages]
[languages.en]
  languageName = 'English'
  weight = 1

[languages.ar]
  languageName = 'Arabic'
  weight = 2

[languages.bn]
  languageName = 'Bengali'
  weight = 3

[languages.bg]
  languageName = 'Bulgarian'
  weight = 4

[languages.zh-cn]
  languageName = 'Chinese - Simplified (China)'
  weight = 5

[languages.zh-tw]
  languageName = 'Chinese - Traditional (Taiwan)'
  weight = 6

[languages.cs]
  languageName = 'Czech'
  weight = 7

[languages.nl]
  languageName = 'Dutch'
  weight = 8

[languages.fi]
  languageName = 'Finnish'
  weight = 9

[languages.fr]
  languageName = 'French'
  weight = 10

[languages.de]
  languageName = 'German'
  weight = 11

[languages.he]
  languageName = 'Hebrew'
  weight = 12

[languages.hu]
  languageName = 'Hungarian'
  weight = 13

[languages.id]
  languageName = 'Indonesian'
  weight = 14

[languages.it]
  languageName = 'Italian'
  weight = 15

[languages.ja]
  languageName = 'Japanese'
  weight = 16

[languages.ko]
  languageName = 'Korean'
  weight = 17

[languages.pl]
  languageName = 'Polish'
  weight = 18

[languages.pt-br]
  languageName = 'Portuguese (Brazil)'
  weight = 19

[languages.pt-pt]
  languageName = 'Portuguese (Portugal)'
  weight = 20

[languages.ro]
  languageName = 'Romanian'
  weight = 21

[languages.ru]
  languageName = 'Russian'
  weight = 22

[languages.sk]
  languageName = 'Slovak'
  weight = 23

[languages.es]
  languageName = 'Spanish (Spain)'
  weight = 24

[languages.sv]
  languageName = 'Swedish'
  weight = 25

[languages.ta]
  languageName = 'Tamil'
  weight = 26

[languages.tr]
  languageName = 'Turkish'
  weight = 27

[languages.uk]
  languageName = 'Ukrainian'
  weight = 28

[languages.vi]
  languageName = 'Vietnamese'
  weight = 29

[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/terraprompt/whatgenerativeai"
  weight = 10

[[menu.after]]
  name = "Contact us"
  url = "https://www.dipankar.name"
  weight = 12
